version: 0.2

phases:
  pre_build: # We'll use pre_build for these tests
    commands:
      - echo "--- Starting Network Diagnostics ---"
      - echo "Attempting to ping google.com..."
      - 'ping -c 3 google.com'
      - echo "--- Ping Test Complete ---"
  build:
    commands:
      - echo "Skipping Docker build for this network test."
  post_build:
    commands:
      - echo "Skipping Docker push for this network test."
