  version: 0.2
  phases:
    install:
      commands:
        - echo "Isntalling network utilities"
        - apt-get update -y
        - apt-get install -y iputils-ping dnsutils
    pre_build:
      commands:
        - echo "Running network diagnostics"
        - 'ping -c 1 google.com'
        - echo "Attempting nslookup for ECR using default DNS" 
        - 'nslookup dkr.ecr.eu-north-1.amazonaws.com'
        - echo "Attempting nslookup for ECR using Google DNS (8.8.8.8)"
        - 'nslookup dkr.ecr.eu-north-1.amazonaws.com 8.8.8.8'
    build:
      commands:
        - echo "Build phase - if nslookup with 8.8.8.8 works, we will try ECR login"
    post_build:
      commands:
        - echo "Post-build phase"
